#!/usr/bin/env python3
"""Generate knowledge/08_data_dictionary_*.md: every provided band with shipped description, official wording, statistics, family and flags."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import rasterio

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from gems25.families import FAMILIES  # noqa: E402
from gems25.features import BASE_NAMES  # noqa: E402
from gems25.paths import data_dir, work_dir  # noqa: E402

OFFICIAL = {  # wording of https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/ (Provided features), read 2026-10-02
    "cond_surf": "Surface conductivity (and depth to conductive base surface)",
    "depth_to_base_surf": "depth to conductive base surface",
    "det_elev": "Detrended elevation", "det_elev_slope": "the slope of detrended elevation",
    "geod_dilaterate": "Dilatation rate", "geod_shearrate": "shear strain rate", "geod_2ndinv": "the second invariant of the strain rate tensor",
    "iso_grav_anom": "Isostatic gravity anomaly", "iso_grav_anom_slope": "the slope of the isostatic gravity anomaly",
    "rtp": "reduced-to-pole magnetic anomaly", "tmi": "total magnetic intensity", "tmi_vg": "the vertical ... slope of total magnetic intensity",
    "tmi_hg": "the ... horizontal slope of total magnetic intensity",
    "deq_n100a15": "Density of earthquakes", "ieq_n100a15": "Density of earthquakes (one official layer; two bands shipped)",
    "mag_anom": "(no matching official wording; the list names a 'top-of-crustal magnetic source depth estimate')",
    "iso_grav_anom_hg": "(not named; derived gravity horizontal gradient)", "iso_grav_anom_vg": "(not named; derived gravity vertical gradient)",
    "tc": "(not in the text list; the page's figure caption calls a left panel 'total radiometric counts per second')",
}
FLAGS = {
    "tc": "IR-25-TC-BAND: shipped description says tilt/curvature; values equal GeoDAWN radiometric TC (Spearman 0.9999)",
    "deq_n100a15": "IR-25-BAND-ALIASES: shipped 'Distance to earthquake' vs official 'Density of earthquakes'",
    "ieq_n100a15": "IR-25-BAND-ALIASES: two earthquake bands vs one official layer",
    "depth_to_base_surf": "IR-25-BAND-ALIASES: shipped 'depth to basement surface' vs official 'depth to conductive base surface'",
    "mag_anom": "IR-25-BAND-ALIASES: no band carries the official 'top-of-crustal magnetic source depth estimate'",
}


def compute_stats() -> dict:
    """Per-band statistics inside the footprint from the prepared work bands (written to evidence/band_stats.json)."""
    import numpy as np

    b = work_dir() / "bands"
    foot = np.load(b / "_footprint.npy")
    out = {}
    for i, n in enumerate(BASE_NAMES, 1):
        a = np.load(b / f"{i:02d}_{n}.npy", mmap_mode="r")
        v = np.asarray(a)[foot]
        ok = np.isfinite(v)
        w = v[ok]
        out[n] = dict(band=i, name=n, nodata_inside=int((~ok).sum()), finite_outside=int(np.isfinite(np.asarray(a)[~foot]).sum()),
                      min=float(w.min()), p01=float(np.percentile(w, 1)), median=float(np.median(w)), p99=float(np.percentile(w, 99)), max=float(w.max()))
    (ROOT / "evidence" / "band_stats.json").write_text(json.dumps(out, indent=1) + "\n")
    return out


def main() -> None:
    cached = ROOT / "evidence" / "band_stats.json"
    stats = json.loads(cached.read_text()) if cached.exists() else compute_stats()
    fam_of = {n: k for k, v in FAMILIES.items() for n in v["base"]}
    L = ["# 08 · Data dictionary (generated by `scripts/build_data_dictionary.py`, 2026-10-02)\n",
         "Source of the bands: the owner mirror of `training_features.tif` (SHA-256 `4371c82e…`, not organizer-authenticated). Official wording is from the "
         "[problem page](https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/). Statistics are inside the 5,167,373-pixel footprint (1st/50th/99th percentile).\n",
         "## Provided features (19 bands, float32, EPSG:32611, 100 m, nodata −3.4028235e38)\n",
         "| # | Band | Shipped description | Official wording | Family | p1 / p50 / p99 | Flag |", "|---|---|---|---|---|---|---|"]
    with rasterio.open(Path(data_dir()) / "training_features.tif") as s:
        for i in range(1, s.count + 1):
            t = s.tags(i)
            n = t["band_name"]
            st = stats.get(n, {})
            rng = f"{st['p01']:.4g} / {st['median']:.4g} / {st['p99']:.4g}" if st else "n/a"
            L.append(f"| {i} | `{n}` | {t['description']} | {OFFICIAL.get(n, '')} | {fam_of.get(n, '?')} | {rng} | {FLAGS.get(n, '')} |")
    L += ["", "## External layers (owner mirror, SHA-256 pinned; derived products)\n",
          "| Layer | Content | Official source | Licence / rights |", "|---|---|---|---|",
          "| `lidar_scarp_features_u8.tif` (12 bands) | per-100 m descriptors from 3DEP 1 m DEM: ex_max, ex_mean, step_max, lapneg_max, lappos_max, downface_max, upface_max, cross_max, relief, coh100, strike, valid (uint8, 0 = no lidar; 706 of 716 tiles) | [USGS 3DEP](https://www.usgs.gov/3d-elevation-program) | 'free of charge and without use restrictions' (USGS page) |",
          "| `geodawn_rad_u8.tif` (K, Th, U, TC) | radiometric grids, uint8 1st–99th percentile | [GeoDAWN, ScienceBase](https://www.sciencebase.gov/catalog/item/657e1d85d34e23d3533209f7), DOI 10.5066/P93LGLVQ | licence line not on the page text read (IR-25-LICENSE-GEODAWN) |",
          "| `geodawn_extensions_u8.tif` (ThK, UK, UTh, TMI_up150) | ratio grids and upward-continued TMI | same | same |",
          "| `gdr_wellspring_in_footprint.csv` | 27,092 spring/well records (temperature, geothermometers, thermal class) inside the footprint; `dist_known_fault_px` is label-derived and is NOT used | [GDR 1391](https://gdr.openei.org/submissions/1391), DOI 10.15121/1881483 | CC BY 4.0 |",
          "| `gdr_qfaults_traces.csv` | INGENIOUS Quaternary fault trace attributes (map scale, slip rate, recency) | same | CC BY 4.0 |",
          "| `gdr_volcanic_vents_in_footprint.csv` | 21 Quaternary vents | same | CC BY 4.0 |",
          "| `labels.tif` / `existing_faults.tif` | 60,988 labelled fault pixels (int8: −1 outside, 0, 1); the two files are byte-identical | INGENIOUS compilation (Ayling et al. 2022, DOI 10.15121/1881483) per the [rules §3.3](https://docs.nlr.gov/docs/fy26osti/96647.pdf) | owner mirror |",
          "| `sample_submission.tif` | footprint template (5,167,373 finite pixels); its 60,988 pixels equal to 1 sit on the labelled faults | DrivenData data page (login) | owner mirror |", ""]
    out = ROOT / "knowledge" / "08_data_dictionary_2026-10-02.md"
    out.write_text("\n".join(L))
    print("wrote", out, len(L), "lines")


if __name__ == "__main__":
    main()
